name: Build and Publish NuGet Package

on:
  push:
    branches:
      - master # Trigger the action only when code is pushed to the main branch
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.x' # Adjust this to your project's .NET version
        
    - name: Execute unit tests
      run: dotnet test
      
    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    # Automatically update version number here if you need. Otherwise, manage it manually in your .csproj file
    
    - name: Pack
      run: dotnet pack --configuration Release --no-build -o out /p:PackageVersion=${{ github.run_number }} # You can adjust versioning strategy

    - name: List directory
      run: ls -R out/

    - name: Push to NuGet
      run: dotnet nuget push out/*.nupkg --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json

      
    - name: Push NuGet package
      run: dotnet nuget push out/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
